name: Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - run: npx quartz build
      - uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -rv --delete
          path: /notes/content
          remote_path: /home/smallweb/smallweb/notes/content
          remote_host: ssh.player.gdn
          remote_user: smallweb
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
  example:
    runs-on: ubuntu-latest
    environment: playground
    permissions:
      actions:     read  # required for qoomon/actions--context action
      deployments: read  # required for qoomon/actions--context action
      contents: read
    steps:
      - uses: qoomon/actions--context@v1
        id: context

      - run: |
          echo "Current Environment: ${{ steps.context.outputs.environment }}"
          echo "Job ID: ${{ steps.context.outputs.job_id }}"
          echo "Job Logs: ${{ steps.context.outputs.job_log_url }}"
