name: Web

on:
  push:
    branches:
      - main

jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
        working-directory: notes
      - run: npm run build
        working-directory: notes
      - uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -rv --delete
          path: www/.vitepress/dist/
          remote_path: /home/smallweb/smallweb/notes/content
          remote_host: ssh.player.gdn
          remote_user: smallweb
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
